### ISSUE TITLE
Question: Can I fork this and make it my own?

### ISSUE THREAD

**Issue by teampsych** [TheAngelReturns/angelbot#1]
First, the fork will **not** be a direct copy of what you have here, I will only use this as a base. Second, how does this even run?

**Comment by alicerunsonfedora** [comment]
This is a Python bot that runs right off of Heroku. I recommend you look at some tutorials online for fully running this software on it.

**Comment by teampsych** [comment]
Where do I define the "bot_key" label and is that for the token?

**Comment by teampsych** [comment]
Also, there is no procfile here, did you use one?

**Comment by alicerunsonfedora** [comment]
There is a profile in the source code. Look for `Procfile`

**Comment by teampsych** [comment]
Okay but this won't run on heroku, the token is simply refusing point blank

**Comment by alicerunsonfedora** [comment]
You need to fetch your own token, silly!

**Comment by teampsych** [comment]
I did, silly! Where do I put it though?

**Comment by Bomiller112** [comment]
Hello,am happy to share my experience so far in trading binary options
have been losing and finding it difficult to make profit in trading for long until i meet [Mr Bo Miller] who help me and gave me the right strategy and winning signals to trade and also i was able to get all my lost fund back from greedy brokers through Him. now i can make a profit of 12000USD weekly through his amazing masterclass strategy feel free to email him on dylanryhan2@gmail.com

**Comment by Bomiller112** [comment]
Hello,am happy to share my experience so far in trading binary options
have been losing and finding it difficult to make profit in trading for long until i meet [Mr Barleyweather] who help me and gave me the right strategy and winning signals to trade and also i was able to get all my lost fund back from greedy brokers through Him. now i can make a profit of 12000USD weekly through his amazing masterclass strategy feel free to email him on barleyweather@gmail.com
